import CreateProjectPage from "./addMoney";

export const metadata = {
  title: "Añadir Fondos",
  description: "Generated by create next app",
};

export default function CreateProject() {
  return (
    <CreateProjectPage />
  );
}
