import CreateProjectPage from "./projectDonate";

export const metadata = {
  title: "Donación",
  description: "Generated by create next app",
};

export default function CreateProject() {
  return (
    <CreateProjectPage />
  );
}
