import CreateProjectPage from "./projectDetails";

export const metadata = {
  title: "Detalles de Proyecto",
  description: "Generated by create next app",
};

export default function CreateProject() {
  return (
    <CreateProjectPage />
  );
}
