import CreateProjectPage from "./CreateProjectPage";

export const metadata = {
  title: "CrearProyecto",
  description: "Generated by create next app",
};

export default function CreateProject() {
  return (
    <CreateProjectPage />
  );
}
