import LoginPage from "./LoginPage";

export const metadata = {
  title: "Inicio de Sesión",
  description: "Generated by create next app",
};

export default function Login() {
  return (
    <LoginPage />
  );
}
