import EditUserPage from "./EditUserPage"

export const metadata = {
  title: "Editar Usuario",
  description: "Generated by create next app",
};

export default function EditUser() {
  return (
    <EditUserPage />
  );
}