import SignupPage from "./SignupPage";

export const metadata = {
  title: "Registro",
  description: "Generated by create next app",
};

export default function SignUp() {
  return (
    <SignupPage />
  );
}