import UpdateProjectPage from "./UpdateProjectPage";

export const metadata = {
  title: "Editar Proyecto",
  description: "Generated by create next app",
};

export default function UpdateProject() {
  return (
    <UpdateProjectPage />
  );
}